defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: True
device: "cuda:0"
seed: 0

# Total Training Length
max_frame_num: 1e7 # max frame (~2 hours)
eval_interval: 5000 # evaluate the policy for every N training steps
save_interval: 2000

# Training Environment
env:
  num_envs: 20 # Number of drones for training
  max_episode_length: 2000
  env_spacing: 4.0 
  num_obstacles: 120
env_dyn:
  num_obstacles: 32 # set to zero if static env is needed
  vel_range: [0.3, 0.5]  # faster obstacles for better training
  local_range: [4.0, 4.0, 3.0]

viewer:
  eye: [18., -18., 16.]
  lookat: [0., 0., 2.]
  resolution: [640, 480]

wandb:
  project: NavRL
  name: navigation_training
  entity: CERLAB-UAV-RL-Navigation
  mode: offline # online
  run_id: #kw9xf9k9
